### ISSUE TITLE
Add `--allow-root` args for jupyter-notebook run

### ISSUE THREAD

**Issue by chusiang** [chusiang/ansible-jupyter.dockerfile#10]
I can't run the jupyter-notebook at jupyter  v4.3.0, maybe I need add the `--allow-root` args in the `docker-entrypoint.sh`.

```
$ docker run -p 8888:8888 -d chusiang/ansible-jupyter
[I 05:03:37.061 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 05:03:37.077 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[C 05:03:37.083 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
```

**Comment by chusiang** [comment]
It's working after I add the `--allow-root` args in the `docker-entrypoint.sh`.

```
$ docker run -p 8888:8888 -d ansible-jupyter:alpine
[I 05:10:14.202 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 05:10:14.215 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 05:10:14.221 NotebookApp] Serving notebooks from local directory: /home
[I 05:10:14.221 NotebookApp] 0 active kernels
[I 05:10:14.221 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/
[I 05:10:14.221 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by syedwajid4** [comment]
what should i do with this error?
All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[C 08:37:43.515 NotebookApp] Running as root is not recommended. Use --allow-root to bypass. can anyone help me in this issue?

**Comment by chusiang** [comment]
Hi @syedwajid4 ,

I have add the `--allow-root` args at https://github.com/chusiang/ansible-jupyter.dockerfile/commit/672be93cf4827d381c35dea0b55c4597aa40c82f commit, the `chusiang/ansible-jupyter` of docker images should be worked.

If you want to use `root` to executive the `jupyter-notebook` command, you can use this command.

```
$ jupyter-notebook --ip 0.0.0.0 --no-browser --allow-root --notebook-dir=/home
```
